Repository ManageIQ/manageiq-providers-scvmm, pull requests merged in 2018-12, with the labels that each got.

#98 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes

#99 Convert FactoryGirl to FactoryBot
  spec/models/manageiq/providers/microsoft/infra_manager/provision/placement_spec.rb
  spec/models/manageiq/providers/microsoft/infra_manager/provision/state_machine_spec.rb
  spec/models/manageiq/providers/microsoft/infra_manager/provision_spec.rb
  spec/models/manageiq/providers/microsoft/infra_manager/provision_workflow_spec.rb
  spec/models/manageiq/providers/microsoft/infra_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/microsoft/infra_manager/refresher_spec.rb
  spec/models/manageiq/providers/microsoft/infra_manager_spec.rb
Labels: dependencies, gaprindashvili/no, hammer/no

#101 Bump master travis.yml to ruby 2.4.5
  .travis.yml
Labels: test
