Repository ManageIQ/manageiq-providers-scvmm, pull requests merged in 2018-05, with the labels that each got.

#76 [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#73 Load Lans efficiently in ProvisionWorkflow
  app/models/manageiq/providers/microsoft/infra_manager/provision_workflow.rb
Labels: refactoring

#77 Bump to ruby 2.4.4 for great justice
  .travis.yml
Labels: test
