Repository ManageIQ/manageiq-providers-scvmm, pull requests merged in 2018-08, with the labels that each got.

#80 Add parent_id to the ActiveRecord select filter
  app/models/manageiq/providers/microsoft/infra_manager/provision_workflow.rb
  spec/models/manageiq/providers/microsoft/infra_manager/provision_workflow_spec.rb
Labels: bug

#82 [Changelog] Update for Sprint 92
  CHANGELOG.md
Labels: documentation

#84 [Changelog] Update for Gaprindashvili-5
  CHANGELOG.md
Labels: documentation

#81 Graph refresh for SCVMM
  app/models/manageiq/providers/microsoft/infra_manager/parser_mixin.rb
  app/models/manageiq/providers/microsoft/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/microsoft/inventory.rb
  app/models/manageiq/providers/microsoft/inventory/collector.rb
  app/models/manageiq/providers/microsoft/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/microsoft/inventory/parser.rb
  app/models/manageiq/providers/microsoft/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/microsoft/inventory/persister.rb
  app/models/manageiq/providers/microsoft/inventory/persister/infra_manager.rb
  config/settings.yml
  spec/models/manageiq/providers/microsoft/infra_manager/refresher_spec.rb
Labels: enhancement
