Repository ManageIQ/manageiq-providers-scvmm, pull requests merged in 2018-11, with the labels that each got.

#93 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_Providers_Scvmm.po
  locale/fr/ManageIQ_Providers_Scvmm.po
  locale/ja/ManageIQ_Providers_Scvmm.po
  locale/pt_BR/ManageIQ_Providers_Scvmm.po
  locale/zh_CN/ManageIQ_Providers_Scvmm.po
Labels: internationalization

#95 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation

#96 Fix missing supports features for guest operations
  app/models/manageiq/providers/microsoft/infra_manager/vm.rb
Labels: bug

#97 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation
