Repository ManageIQ/manageiq-providers-scvmm, pull requests merged in 2019-11, with the labels that each got.

#141 Subclass require_snapshot_for_scan? method
  app/models/manageiq/providers/microsoft/infra_manager/vm_or_template_shared/scanning.rb
Labels: refactoring

#143 Add and subclass scan_timeout_adjustment_multiplier method
  app/models/manageiq/providers/microsoft/infra_manager/vm_or_template_shared/scanning.rb
Labels: refactoring, smart state

#145 Remove zanata from README
  README.md
Labels: cleanup

#147 Move SCVMM-specific part of vm_scan_spec.rb from the core repo
  spec/models/manageiq/providers/microsoft/infra_manager/vm_scan_spec.rb
Labels: refactoring, smart state, test

#148 Rely on the default implementation of .ems_class
  app/models/manageiq/providers/microsoft/infra_manager/refresh_worker.rb
Labels: refactoring

#152 Expand VmScan specs before refactoring VmScan
  spec/models/manageiq/providers/microsoft/infra_manager/vm_scan_spec.rb
Labels: test, wip
