Repository ManageIQ/manageiq-providers-scvmm, pull requests merged in 2019-07, with the labels that each got.

#124 Add a rubocop channel to the codeclimate config
  .codeclimate.yml
Labels: dependencies

#125 Disable support for restart/shutdown if VM is off
  app/models/manageiq/providers/microsoft/infra_manager/vm.rb
Labels: blocker, bug

#127 Fix the SCVMM template type, was just MiqTemplate
  app/models/manageiq/providers/microsoft/inventory/persister/infra_manager.rb
  spec/models/manageiq/providers/microsoft/infra_manager/refresher_spec.rb
Labels: bug

#131 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#128 Ignore powershell.log files after running specs
  .gitignore
Labels: developer

#129 Remove legacy refresh code
  app/models/manageiq/providers/microsoft/infra_manager.rb
  app/models/manageiq/providers/microsoft/infra_manager/refresh_parser.rb
  app/models/manageiq/providers/microsoft/infra_manager/refresher.rb
  config/settings.yml
  spec/models/manageiq/providers/microsoft/infra_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/microsoft/infra_manager/refresher_spec.rb
Labels: cleanup, ivanchuk/no
