Repository ManageIQ/manageiq-providers-scvmm, pull requests merged in 2019-05, with the labels that each got.

#113 Finish fixing graph/classic refresh inconsistencies
  app/models/manageiq/providers/microsoft/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/microsoft/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/microsoft/infra_manager/refresher_spec.rb
Labels: enhancement

#111 Use the relationship collections from core
  app/models/manageiq/providers/microsoft/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/microsoft/inventory/persister/infra_manager.rb
  spec/models/manageiq/providers/microsoft/infra_manager/refresher_spec.rb
Labels: refactoring

#114 Simplify infra collection definitions
  app/models/manageiq/providers/microsoft/inventory/persister/infra_manager.rb
Labels: cleanup

#115 Default to graph refresh
  config/settings.yml
Labels: enhancement

#117 Change plugin common methods to class methods
  lib/manageiq/providers/scvmm/engine.rb
Labels: refactoring

#116 Bump master travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#118 Fix an issue building host_guest_device cd drive
  app/models/manageiq/providers/microsoft/inventory/parser/infra_manager.rb
Labels: bug

#119 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test
