Repository ManageIQ/manageiq-providers-scvmm, pull requests merged in 2020-10, with the labels that each got.

#166 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#167 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-scvmm.gemspec
Labels: developer, enhancement

#168 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer
