Repository ManageIQ/manageiq-providers-scvmm, pull requests merged in 2020-05, with the labels that each got.

#157 Fix VMDBLogger initialize for ruby 2.7
  spec/models/manageiq/providers/microsoft/infra_manager/powershell_spec.rb
Labels: bug

#158 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#159 Removing deprecated Gemnasium badge
  README.md
Labels: developer
