Repository ManageIQ/manageiq-providers-scvmm, pull requests merged in 2021-03, with the labels that each got.

#183 Don't manually set miq_template's model_class
  app/models/manageiq/providers/microsoft/inventory/persister/infra_manager.rb
Labels: refactoring

#184 Handle missing VM VMCPath
  app/models/manageiq/providers/microsoft/inventory/parser/infra_manager.rb
Labels: bug, ivanchuk/yes?, jansa/yes?, kasparov/yes?, lasker/yes?

#186 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#180 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-microsoft_infra_manager_refresh.target
  build/systemd_units/manageiq-providers-microsoft_infra_manager_refresh@.service
Labels: technical debt
